#!/bin/bash
# Generate pattern list table for README.md
# Reads pattern.md files to build markdown tables with Ontosphere links.
# Output is meant to replace the AUTO-GENERATED block in README.md.

REPO_BASE="https://raw.githubusercontent.com/ThHanke/quay/main"
ONTOSPHERE="https://thhanke.github.io/ontosphere"
PATTERNS_DIR="$(dirname "$0")/../patterns"

echo "<!-- AUTO-GENERATED by src/scripts/generate-pattern-list.sh — do not edit manually -->"
echo ""
echo "### Git-Annex Remotes"
echo ""
echo "| Pattern | Description | Ontosphere |"
echo "|---------|-------------|------------|"

for f in $(find "$PATTERNS_DIR/git-annex-remotes" -name 'pattern.md' 2>/dev/null | sort); do
  dir=$(basename $(dirname "$f"))
  title=$(head -1 "$f" | sed 's/^# //')
  desc=$(sed -n '/^## Description$/,/^## /{/^## /!p}' "$f" | sed '/^$/d' | head -1 | sed 's/^ *//' | sed 's/\([^.]*\.\).*/\1/')
  rdfurl="${REPO_BASE}/src/patterns/git-annex-remotes/${dir}/shape-data.ttl"
  link="${ONTOSPHERE}/?rdfUrl=${rdfurl}"
  echo "| [${title}](src/patterns/git-annex-remotes/${dir}/pattern.md) | ${desc} | [Open](${link}) |"
done

echo ""
echo "### Generic Data Access Examples"
echo ""
echo "| Pattern | Description | Ontosphere |"
echo "|---------|-------------|------------|"

for f in $(find "$PATTERNS_DIR/generic-examples" -name 'pattern.md' 2>/dev/null | sort); do
  dir=$(basename $(dirname "$f"))
  title=$(head -1 "$f" | sed 's/^# //')
  desc=$(sed -n '/^## Description$/,/^## /{/^## /!p}' "$f" | sed '/^$/d' | head -1 | sed 's/^ *//' | sed 's/\([^.]*\.\).*/\1/')
  rdfurl="${REPO_BASE}/src/patterns/generic-examples/${dir}/shape-data.ttl"
  link="${ONTOSPHERE}/?rdfUrl=${rdfurl}"
  echo "| [${title}](src/patterns/generic-examples/${dir}/pattern.md) | ${desc} | [Open](${link}) |"
done

echo ""
echo "<!-- END AUTO-GENERATED -->"
