#!/bin/bash
# Generate pattern list table for README.md
# Reads pattern.md and shape-data.ttl files to build markdown tables
# with Ontosphere links and feature badges.
# Output is meant to replace the AUTO-GENERATED block in README.md.

REPO_BASE="https://raw.githubusercontent.com/ThHanke/quay/main"
ONTOSPHERE="https://thhanke.github.io/ontosphere"
PATTERNS_DIR="$(dirname "$0")/../patterns"

# Detect features from shape-data.ttl
detect_features() {
  local ttl="$1"
  local features=""
  grep -q "odrl:" "$ttl" 2>/dev/null && features="${features} ODRL"
  grep -q "uptimePercentage\|recoveryTime\|replicationFactor" "$ttl" 2>/dev/null && features="${features} SQ"
  grep -q "rateLimit" "$ttl" 2>/dev/null && features="${features} Rate"
  grep -q "retentionPeriod" "$ttl" 2>/dev/null && features="${features} Ret"
  grep -q "storageJurisdiction" "$ttl" 2>/dev/null && features="${features} Geo"
  grep -q "encryptionAtRest" "$ttl" 2>/dev/null && features="${features} Enc"
  grep -q "conformsTo" "$ttl" 2>/dev/null && features="${features} Schema"
  grep -q "spdx:checksum" "$ttl" 2>/dev/null && features="${features} Chk"
  echo "$features" | sed 's/^ //'
}

MAX_DESC=80

truncate_desc() {
  local s="$1"
  if [ ${#s} -le $MAX_DESC ]; then
    echo "$s"
  else
    echo "${s:0:$MAX_DESC}" | sed 's/ [^ ]*$/…/'
  fi
}

echo "<!-- AUTO-GENERATED by src/scripts/generate-pattern-list.sh — do not edit manually -->"
echo ""
echo "### Git-Annex Remotes"
echo ""
echo "| Pattern | Description | Features | Ontosphere |"
echo "|---------|-------------|----------|------------|"

for f in $(find "$PATTERNS_DIR/git-annex-remotes" -name 'pattern.md' 2>/dev/null | sort); do
  dir=$(basename $(dirname "$f"))
  title=$(head -1 "$f" | sed 's/^# //')
  desc=$(sed -n '/^## Description$/,/^## /{/^## /!p}' "$f" | sed '/^$/d' | head -1 | sed 's/^ *//' | sed 's/\([^.]*\.\).*/\1/' | sed 's/^Git-annex [^ ]* special remote //' | sed 's/^Git-annex [^ ]* remote //' | sed 's/^./\U&/')
  desc=$(truncate_desc "$desc")
  ttl="$(dirname "$f")/shape-data.ttl"
  features=$(detect_features "$ttl")
  rdfurl="${REPO_BASE}/src/patterns/git-annex-remotes/${dir}/shape-data.ttl"
  link="${ONTOSPHERE}/?rdfUrl=${rdfurl}"
  echo "| [${title}](src/patterns/git-annex-remotes/${dir}/pattern.md) | ${desc} | ${features} | [Open](${link}) |"
done

echo ""
echo "### Generic Data Access Examples"
echo ""
echo "| Pattern | Description | Features | Ontosphere |"
echo "|---------|-------------|----------|------------|"

for f in $(find "$PATTERNS_DIR/generic-examples" -name 'pattern.md' 2>/dev/null | sort); do
  dir=$(basename $(dirname "$f"))
  title=$(head -1 "$f" | sed 's/^# //')
  desc=$(sed -n '/^## Description$/,/^## /{/^## /!p}' "$f" | sed '/^$/d' | head -1 | sed 's/^ *//' | sed 's/\([^.]*\.\).*/\1/' | sed 's/^Git-annex [^ ]* special remote //' | sed 's/^Git-annex [^ ]* remote //' | sed 's/^./\U&/')
  desc=$(truncate_desc "$desc")
  ttl="$(dirname "$f")/shape-data.ttl"
  features=$(detect_features "$ttl")
  rdfurl="${REPO_BASE}/src/patterns/generic-examples/${dir}/shape-data.ttl"
  link="${ONTOSPHERE}/?rdfUrl=${rdfurl}"
  echo "| [${title}](src/patterns/generic-examples/${dir}/pattern.md) | ${desc} | ${features} | [Open](${link}) |"
done

echo ""
echo "Feature key: **ODRL** policy, **SQ** service quality metrics, **Rate** limit, **Ret** retention, **Geo** jurisdiction, **Enc** encryption at rest, **Schema** conformsTo link, **Chk** SPDX checksum"
echo ""
echo "<!-- END AUTO-GENERATED -->"
